In [2]:
import pandas as pd 
from sklearn.datasets import load_wine

In [3]:
wine=load_wine()

In [4]:
dir(wine)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [8]:
df=pd.DataFrame(wine.data,columns=wine.feature_names)
df

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0

In [10]:
df['target']=wine.target
df

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0,2
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0,2
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0,2
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0,2
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0,2

In [14]:
df['target_names']=df.target.apply(lambda x : wine.target_names[x])
df

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target,target_names
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0,class_0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0,class_0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0,class_0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0,class_0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0,class_0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0,2,class_2
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0,2,class_2
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0,2,class_2
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0,2,class_2
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0,2,class_2

In [16]:
x=df.drop(['target_names','target'],axis='columns')
x

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0

In [17]:
y=df.target
y

0      0
1      0
2      0
3      0
4      0
      ..
173    2
174    2
175    2
176    2
177    2
Name: target, Length: 178, dtype: int64

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB

In [21]:
model1=GaussianNB()
model2=MultinomialNB()
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2)

In [22]:
model1.fit(xtrain,ytrain)
model2.fit(xtrain,ytrain)

MultinomialNB()

In [23]:
model1.score(xtest,ytest)

0.9444444444444444

In [24]:
model2.score(xtest,ytest)

0.8333333333333334

In [25]:
from sklearn.model_selection import cross_val_score

In [27]:
cross_val_score(model1,xtest,ytest,cv=6)

array([1.        , 0.83333333, 0.83333333, 1.        , 1.        ,
       0.83333333])

In [28]:
cross_val_score(model2,xtest,ytest,cv=6)

array([1.        , 0.66666667, 0.83333333, 0.66666667, 0.5       ,
       0.83333333])

In [30]:
model1.predict_proba(xtest)

array([[1.00000000e+00, 6.60052090e-12, 1.98484803e-40],
       [5.49862575e-18, 1.00000000e+00, 5.14933796e-31],
       [2.74819883e-26, 2.76373914e-21, 1.00000000e+00],
       [3.28255657e-30, 7.15226066e-06, 9.99992848e-01],
       [1.00000000e+00, 1.81488052e-17, 3.10182769e-47],
       [5.61131310e-23, 4.81386005e-07, 9.99999519e-01],
       [3.27601280e-15, 9.99999922e-01, 7.77034971e-08],
       [2.34506639e-19, 1.88279057e-03, 9.98117209e-01],
       [1.87453834e-11, 1.00000000e+00, 2.31466401e-15],
       [1.14116776e-22, 4.42260792e-06, 9.99995577e-01],
       [1.02388925e-18, 7.83539884e-12, 1.00000000e+00],
       [3.60461314e-15, 9.38762469e-02, 9.06123753e-01],
       [9.99993027e-01, 6.97338555e-06, 4.27146464e-23],
       [9.99999999e-01, 1.21089050e-09, 1.20550195e-39],
       [1.00000000e+00, 1.10868057e-10, 1.86048366e-48],
       [2.73884043e-24, 3.35213989e-05, 9.99966479e-01],
       [2.23001538e-09, 9.99999998e-01, 4.84395100e-18],
       [9.99999999e-01, 1.16054428e-09, 1.03518248e-47],
       [2.24154963e-01, 7.75845037e-01, 4.42968218e-36],
       [1.03021042e-18, 4.62424613e-05, 9.99953758e-01],
       [2.17833849e-03, 9.97821662e-01, 6.30252546e-23],
       [9.61054464e-01, 3.89455357e-02, 2.08561922e-21],
       [9.86388009e-01, 1.36119907e-02, 1.59687062e-31],
       [4.22213017e-20, 4.27608100e-04, 9.99572392e-01],
       [1.38298916e-07, 9.99999862e-01, 7.14457337e-34],
       [1.00000000e+00, 8.64635467e-11, 6.71524706e-39],
       [2.53376635e-13, 1.00000000e+00, 1.39407288e-14],
       [9.99999948e-01, 5.16008567e-08, 1.49606303e-42],
       [9.99995328e-01, 4.67248636e-06, 1.55331498e-41],
       [3.04146476e-03, 9.96958535e-01, 5.80052767e-18],
       [1.12386058e-31, 1.51545148e-07, 9.99999848e-01],
       [8.71430612e-07, 9.99999129e-01, 1.15317158e-13],
       [1.21399921e-24, 4.87274055e-21, 1.00000000e+00],
       [2.42305236e-09, 9.99999998e-01, 3.57284651e-25],
       [4.96006424e-01, 5.03993576e-01, 5.12641090e-17],
       [1.90608170e-14, 1.00000000e+00, 1.23667436e-19]])

In [31]:
model2.predict_proba(xtest)

array([[1.00000000e+00, 9.82944564e-16, 5.72990821e-11],
       [5.05570624e-15, 9.99828651e-01, 1.71348585e-04],
       [1.19654323e-07, 3.51087027e-04, 9.99648793e-01],
       [2.13299057e-03, 1.08484884e-03, 9.96782161e-01],
       [1.00000000e+00, 2.42260845e-32, 2.59187846e-23],
       [3.54816459e-08, 3.28172232e-02, 9.67182741e-01],
       [3.72640765e-09, 9.64757086e-01, 3.52429106e-02],
       [1.13809827e-08, 1.88251687e-01, 8.11748302e-01],
       [7.46116080e-24, 9.99984330e-01, 1.56698511e-05],
       [2.29337238e-11, 3.75694527e-01, 6.24305473e-01],
       [2.02012370e-20, 9.37477934e-01, 6.25220661e-02],
       [8.55069922e-11, 6.71436463e-01, 3.28563537e-01],
       [1.00000000e+00, 1.31817012e-14, 2.94752049e-10],
       [1.00000000e+00, 1.18858943e-20, 8.15563745e-15],
       [1.00000000e+00, 1.08414391e-23, 8.20746346e-18],
       [1.39094369e-11, 3.74943759e-01, 6.25056241e-01],
       [2.70858165e-20, 9.99983450e-01, 1.65503986e-05],
       [1.00000000e+00, 1.18907318e-17, 4.68676785e-13],
       [8.43803047e-07, 9.70024192e-01, 2.99749640e-02],
       [9.74042018e-13, 7.01699515e-01, 2.98300485e-01],
       [1.40664102e-06, 9.13082110e-01, 8.69164831e-02],
       [1.54547342e-07, 8.43420198e-01, 1.56579648e-01],
       [9.98857531e-01, 5.17724460e-05, 1.09069667e-03],
       [2.72914699e-13, 7.78776996e-01, 2.21223004e-01],
       [1.83365910e-15, 9.99885440e-01, 1.14559790e-04],
       [1.00000000e+00, 2.73388163e-24, 1.86990180e-17],
       [7.67740737e-21, 9.99950898e-01, 4.91021956e-05],
       [1.63774871e-05, 8.09383137e-01, 1.90600486e-01],
       [1.00000000e+00, 2.72222270e-14, 8.98004077e-11],
       [5.85246274e-04, 5.55719711e-01, 4.43695043e-01],
       [1.65730990e-13, 3.99180022e-01, 6.00819978e-01],
       [1.68188175e-07, 9.14325315e-01, 8.56745171e-02],
       [1.54845493e-06, 3.79365042e-05, 9.99960515e-01],
       [1.35832782e-12, 9.97319700e-01, 2.68029967e-03],
       [1.04831539e-05, 5.26411929e-01, 4.73577588e-01],
       [8.83278122e-10, 9.73731776e-01, 2.62682226e-02]])